### ISSUE TITLE
Uncaught Error: Cannot find module './src/cat'

### ISSUE THREAD

**Issue by kevinguard** [danday74/git-diff#2]
When attempting to import the library, I keep getting the following error:

`Uncaught Error: Cannot find module './src/cat'`

No matter how I import it, I face the same error:

`import * as gitDiff from "git-diff";` or `const gitDiff = require("git-diff");`

Note: I have `git` on my local machine but my intention is to use the fallback `fake diff` functionality on production. Thanks!

**Comment by danday74** [comment]
hey there

There's no src folder in the project and there's only one reference to "cat" in travis.yml which should not cause this error

Could you provide a stack trace - maybe its a failing dependency

I'll bump the deps in the hope it fixes it

Also what version of Node are you using?

I assume since you can't import it that theres no known error with the actual code itself as far as you know?

PS I've also fixed another issue today which may or may not help

Let me know and try with the 2.0.5 release

**Comment by kevinguard** [comment]
Thank you Daniel! I will re-install all deps and will try the new release once it's published! Cheers!

**Comment by danday74** [comment]
just published now

**Comment by danday74** [comment]
argh windows build failing, shouldnt effect you - will be doing a 2.0.6 release in the next few mins

**Comment by kevinguard** [comment]
With `2.0.5` I still see the crash and I think it has nothing to do with your library. Here is the stack trace:
```
_prelude.js:1 Uncaught Error: Cannot find module './src/cat'
    at s (http://localhost:14238/javascripts/main.js:1:159)
    at http://localhost:14238/javascripts/main.js:1:316
    at http://localhost:14238/javascripts/main.js:136564:3
    at Array.forEach (native)
    at Object.<anonymous> (http://localhost:14238/javascripts/main.js:136563:23)
    at Object.930../commands (http://localhost:14238/javascripts/main.js:136695:4)
    at s (http://localhost:14238/javascripts/main.js:1:265)
    at http://localhost:14238/javascripts/main.js:1:316
    at Object.426.shelljs (http://localhost:14238/javascripts/main.js:64371:13)
    at s (http://localhost:14238/javascripts/main.js:1:265)
```
From going into the published JS file to frontend, I clearly see the missing module error but it doesn't say anything about what module is missing!

**Comment by kevinguard** [comment]
I opened an internal ticket for our web platform team to see if something extra I need to do. Feel free to close this ticket unless you are interested in knowing the final outcome :-)

**Comment by danday74** [comment]
Looks like a shelljs issue.

Just taken a peek inside shelljs.

There's a file ... /node_modules/shelljs/src/cat.js

Looks like something is trying to load that but cant

I will close this off but if you find it to be an issue with this library let me know and I'll fix it up ASAP

Thanks :)

**Comment by noahehall** [comment]
FYI: shelljs@0.8.4/node_modules/shelljs/shell.js

```
// Load all default commands
require('./commands').forEach(function (command) {
  require('./src/' + command);
});
```

**Comment by mxro** [comment]
Issue in shelljs project for reference: https://github.com/shelljs/shelljs/issues/1035 - marked as won't fix ` We do not support JavaScript bundler tools because they make incorrect assumptions about our project structure and fail to include modules we require.`

**Comment by KaKi87** [comment]
Hello,
Why was this issue closed ?
Since this module has a fallback to a fake git diff generator, browser environments should profit from it.
Thanks

**Comment by AlexanderLill** [comment]
I fixed it by forking `shelljs` and modifying a few lines: https://github.com/shelljs/shelljs/pull/1161#issuecomment-2328210239
